const Strings = {
  appTilte: "Expense Wallet",
  incomeAmount: "Income",
  balanceAmount: "Balance",
  spentAmount: " Spent",
  expenseList: "Expenses",
  addExpense: "Add Expense",
  name: "Name of Expense",
  category: "Category",
  cost: "Cost",
  addButton: "Add New Expense",
  currency: "SGD",
  Edit: "Edit",
  save: "Save",
  budget: "Budget:",
  date: "Date of Expense",
  food: "Food",
  medical: "Medical/Healthcare",
  grocery: "Groceries",
  clothing: "Clothing",
  transportation: "Transportation",
  housing: "Housing",
  membership: "Membership",
  entertainment: "Entertainment",
  others: "Others",
  week: "This Week",
  thirtyDays: "Last 30 Days",
  sixMonths: "Last 6 Months",
  oneYear: "Last 1 Year",
  chart: "Visualization Chart",
};

export default Strings;
